"""Core domain enums + state machine."""

from __future__ import annotations

from enum import Enum


class PipelineStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    METADATA_SAVED = "METADATA_SAVED"
    DOWNLOAD_PENDING = "DOWNLOAD_PENDING"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADED = "DOWNLOADED"
    AUDIO_VALIDATED = "AUDIO_VALIDATED"
    TRANSCRIPTION_PENDING = "TRANSCRIPTION_PENDING"
    TRANSCRIBING = "TRANSCRIBING"
    TRANSCRIBED = "TRANSCRIBED"
    ROMANIZATION_PENDING = "ROMANIZATION_PENDING"
    ROMANIZING = "ROMANIZING"
    ROMANIZED = "ROMANIZED"
    GRADING_PENDING = "GRADING_PENDING"
    GRADING = "GRADING"
    COMPLETE = "COMPLETE"
    # terminal / problem
    NO_RECORDING = "NO_RECORDING"
    NO_SPEECH = "NO_SPEECH"
    UNGRADABLE = "UNGRADABLE"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    ROMANIZATION_FAILED = "ROMANIZATION_FAILED"
    GRADING_FAILED = "GRADING_FAILED"
    BLOCKED = "BLOCKED"


TERMINAL_STATES = frozenset({
    PipelineStatus.COMPLETE,
    PipelineStatus.NO_RECORDING,
    PipelineStatus.NO_SPEECH,
    PipelineStatus.UNGRADABLE,
    PipelineStatus.NOT_ELIGIBLE,
    PipelineStatus.DOWNLOAD_FAILED,
    PipelineStatus.TRANSCRIPTION_FAILED,
    PipelineStatus.ROMANIZATION_FAILED,
    PipelineStatus.GRADING_FAILED,
    PipelineStatus.BLOCKED,
})

#: Next status to resume from after a crash at a given state.
#: Non-terminal work states resume at the idempotent "start" of that phase.
RESUME_FROM: dict[str, str] = {
    "DISCOVERED": "DOWNLOAD_PENDING",
    "METADATA_SAVED": "DOWNLOAD_PENDING",
    "DOWNLOAD_PENDING": "DOWNLOAD_PENDING",
    "DOWNLOADING": "DOWNLOAD_PENDING",  # re-attempt download; dedupe prevents dupes
    "DOWNLOADED": "TRANSCRIPTION_PENDING",
    "AUDIO_VALIDATED": "TRANSCRIPTION_PENDING",
    "TRANSCRIPTION_PENDING": "TRANSCRIPTION_PENDING",
    "TRANSCRIBING": "TRANSCRIPTION_PENDING",
    "TRANSCRIBED": "ROMANIZATION_PENDING",
    "ROMANIZATION_PENDING": "ROMANIZATION_PENDING",
    "ROMANIZING": "ROMANIZATION_PENDING",
    "ROMANIZED": "GRADING_PENDING",
    "GRADING_PENDING": "GRADING_PENDING",
    "GRADING": "GRADING_PENDING",
}

RETRYABLE_STATES = frozenset({
    PipelineStatus.DOWNLOAD_FAILED,
    PipelineStatus.TRANSCRIPTION_FAILED,
    PipelineStatus.ROMANIZATION_FAILED,
    PipelineStatus.GRADING_FAILED,
    PipelineStatus.BLOCKED,
})


class CanonicalStatus(str, Enum):
    ANSWERED = "ANSWERED"
    NO_ANSWER = "NO_ANSWER"
    BUSY = "BUSY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class Direction(str, Enum):
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"
    UNKNOWN = "UNKNOWN"


class JobType(str, Enum):
    DOWNLOAD = "DOWNLOAD"
    TRANSCRIBE = "TRANSCRIBE"
    ROMANIZE = "ROMANIZE"
    GRADE = "GRADE"
    REPORT = "REPORT"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    LEASED = "LEASED"
    DONE = "DONE"
    FAILED = "FAILED"


class ErrorCode(str, Enum):
    JAZZ_AUTH_FAILED = "JAZZ_AUTH_FAILED"
    JAZZ_PAGE_CHANGED = "JAZZ_PAGE_CHANGED"
    JAZZ_TIMEOUT = "JAZZ_TIMEOUT"
    JAZZ_DOWNLOAD_FAILED = "JAZZ_DOWNLOAD_FAILED"
    JAZZ_BLOCKED = "JAZZ_BLOCKED"
    JAZZ_AUTH_BLOCKED = "JAZZ_AUTH_BLOCKED"
    AUDIO_INVALID = "AUDIO_INVALID"
    AUDIO_TOO_LARGE = "AUDIO_TOO_LARGE"
    OPENAI_RATE_LIMITED = "OPENAI_RATE_LIMITED"
    OPENAI_TRANSCRIPTION_FAILED = "OPENAI_TRANSCRIPTION_FAILED"
    ROMANIZATION_SCHEMA_FAILED = "ROMANIZATION_SCHEMA_FAILED"
    GRADING_SCHEMA_FAILED = "GRADING_SCHEMA_FAILED"
    APPWRITE_UNAVAILABLE = "APPWRITE_UNAVAILABLE"
    JOB_LEASE_CONFLICT = "JOB_LEASE_CONFLICT"
    UNKNOWN = "UNKNOWN"
